<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>

    <!-- Swagger -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />

    <!-- JWT -->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />

    <!-- Logging -->
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Structure.Infrastructure\Structure.Infrastructure.csproj" />
    <ProjectReference Include="..\Structure.MediatR\Structure.MediatR.csproj" />
    <ProjectReference Include="..\Structure.Data\Structure.Data.csproj" />
  </ItemGroup>

</Project>